### ISSUE TITLE
Type 'unknown' with circular references

### ISSUE THREAD

**Issue by EilifAkerjordet** [saiichihashimoto/sanity-typed-schema-builder#138] opened 2022-07-21 07:58 UTC
Hi!

I just ran into this issue, where I have a circular reference (see image), which works fine in the studio, but the schema builder gives my type "unknown" for all the schemas in the circle. Break the circle, and all the types work fine. Just wondering if anyone has a solution to this?

<img width="907" alt="Screen Shot 2022-07-20 at 11 46 56 AM" src="https://user-images.githubusercontent.com/64464354/180161250-81f0f793-ab17-4618-b99e-488b89590607.png">

**Comment by saiichihashimoto** [comment] 2022-07-21 15:05
This is a duplicate of #114 but the long and short of it is that inferred recursive types isn't really possible. Somehow, the typescript loop has to be manually defined. Even the builder plan doesn't really seem to solve the problem. Either way, will continue this in #114.

**Closed by saiichihashimoto** 2022-07-21 15:05 UTC

**Comment by ElektrikSpark** [comment] 2022-10-14 09:47
I thought I would need to define circular references, but then I read that "references are always bi-directional" in Sanity. https://www.sanity.io/docs/connected-content
